version = 1
SPDX-PackageName = "linyaps-box"
SPDX-PackageSupplier = "UnionTech Software Technology Co., Ltd."
SPDX-PackageDownloadLocation = "https://github.com/OpenAtom-Linyaps/linyaps-box"
SPDX-PackageLicenseConcluded = "LGPL-3.0-or-later"

[[annotations]]
path = [
    "CMakeLists.txt",
    "src/**/CMakeLists.txt",
    "tests/**/CMakeLists.txt",
    "CMakePresets.json",
    ".gitignore",
    "tests/**/.gitignore",
    ".clang-format",
    ".cmake-format.py",
    "cmake.external/CLI11/**",
    "cmake.external/nlohmann_json/**",
    "cmake.external/zeus_expected/**",
    "cmake.external/fmt/Findfmt.cmake",
    "external/CLI11/CMakeLists.txt",
    "external/nlohmann_json/CMakeLists.txt",
    "external/zeus_expected/CMakeLists.txt",
]
precedence = "closest"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    ".github/**",
    ".gitlab-ci.yml",
    ".obs/workflows.yml",
    "tests/ll-box-st/*.json",
    "tests/ll-box-st/*.txt",
    "tests/ll-box-ut/data/**",
]

exclude = ["**/cmake_test_discovery_*.json"]
precedence = "closest"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["README.md", "README.zh_CN.md"]
precedence = "closest"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["cmake/CPM.cmake"]
precedence = "override"
SPDX-FileCopyrightText = "2019-2023 Lars Melchior and contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["external/nlohmann_json/include/**"]
precedence = "override"
SPDX-FileCopyrightText = "2013-2025 Niels Lohmann <https://nlohmann.me>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["external/CLI11/include/**"]
precedence = "override"
SPDX-FileCopyrightText = "2017-2026 University of Cincinnati, developed by Henry Schreiner under NSF AWARD 1414736."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["external/zeus_expected/include/**"]
precedence = "override"
SPDX-FileCopyrightText = "2024 zeus-cpp"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["external/fmt/**", "cmake.external/fmt/JoinPaths.cmake"]
precedence = "override"
SPDX-FileCopyrightText = "2012 - present, Victor Zverovich and {fmt} contributors"
SPDX-License-Identifier = "MIT"
