name: 'Build'

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    name: Build Source Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential pkgconf libcap-dev \
                                  libseccomp-dev nlohmann-json3-dev libcli11-dev libgtest-dev \
                                  libsystemd-dev

      - name: Configure and Build Project
        run: |
          cmake --workflow --preset=ci
