name: 'Static Analysis'

on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan-build:
    name: scan-build
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Build Dependencies
        uses: ./.github/actions/setup-deps

      - name: Install Clang analysis tools
        run: sudo apt-get install -y clang clang-tools

      - name: Clang Static Analyzer
        run: ./tools/analyzer.sh

      - name: Upload scan-build report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: scan-build-report
          path: build-analyzer/scan-build-report
          if-no-files-found: ignore
